version: "3"
services:
  4linux-angular:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-server
    ports:
      - "4200:4200"
    volumes:
      - '/app/node_modules'
      - ".:/app"